# Generated by Django 5.1.3 on 2024-11-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tripduration', models.TextField(blank=True, null=True)),
                ('starttime', models.TextField(blank=True, null=True)),
                ('stoptime', models.TextField(blank=True, null=True)),
                ('start_station_id', models.BigIntegerField(blank=True, null=True)),
                ('start_station_name', models.TextField(blank=True, null=True)),
                ('start_station_latitude', models.FloatField(blank=True, null=True)),
                ('start_station_longitude', models.FloatField(blank=True, null=True)),
                ('end_station_id', models.BigIntegerField(blank=True, null=True)),
                ('end_station_name', models.TextField(blank=True, null=True)),
                ('end_station_latitude', models.FloatField(blank=True, null=True)),
                ('end_station_longitude', models.FloatField(blank=True, null=True)),
                ('bikeid', models.BigIntegerField(blank=True, null=True)),
                ('membership_type', models.TextField(blank=True, null=True)),
                ('usertype', models.TextField(blank=True, null=True)),
                ('birth_year', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TRIP',
                'managed': False,
            },
        ),
    ]
